name: Feature request
about: Suggest an idea for this project
labels: Enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when ...
    validations:
      required: true
  - type: textarea
      id: relevant-issues
      attributes:
        label: Relevant issues
        description: Did you find any existing issues relevant to this one? If you found the same issue, please contribute to that one instead of making a duplicate.
  - type: textarea
      id: solution-description
      attributes:
        label: Describe the solution you'd like
        description: A clear and concise description of what you want to happen. Please request only one feature per issue, do not combine different features (even if loosely related) into a single issue.
      validations:
        required: true
  - type: textarea
      id: alternatives-considered
      attributes:
        label: Describe alternatives you've considered
        description: A clear and concise description of any alternative solutions or features you've considered.
      validations:
        required: true
  - type: textarea
      id: additional-context
      attritbutes:
        label: Additional context
        description: Add any other context about the problem here.
