name: Tweak
about: Small modification to existing behavior
labels: Tweak
body:
  - type: textarea
      id: description
      attributes:
        label: Is your tweak request related to a problem? Please describe.
        description: A clear and concise description of what the problem is. Ex. I'm always frustrated when ...
      validations:
        required: true
  - type: textarea
      id: tweak-description
      attributes:
        label: Describe what would you like tweaked
        description: A clear and concise description of what you want to happen.
      validations:
        required: true
  - type: textarea
      id: alternatives-considered
      attributes:
        label: Describe alternatives you've considered
        description: A clear and concise description of any alternative solutions or features you've considered.
      validations:
        required: true
  - type: textarea
      id: additional-context
      attritbutes:
        label: Additional context
        description: Add any other context about the problem here.
